### ISSUE TITLE
Failed to download a torrent: missing node.js

### ISSUE THREAD

**Issue by CyrillePierre** [linuxserver/docker-sickchill#5]
I've tried to switch my configuration between `linuxserver/sickrage` and `linuxserver/sickchill`.
My current `docker-compose.yml` is:
```yaml
version: '2'
services:
  sickrage:
    image: linuxserver/sickchill
    network_mode: bridge
    restart: always
    environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Paris
    volumes:
    - /data/containers/sr/config:/config
    - /data/containers/dl/downloads/complete:/downloads
    - /data/containers/media/series:/tv
    - /data/containers/dl/watch:/watch
    - /etc/localtime:/etc/localtime:ro
    mem_limit: 512M
    memswap_limit: 0
```
When a torrent is found, the download fails with the following message (sickchill logs):
```
2019-04-15 11:58:49 SEARCHQUEUE-MANUAL-121361 :: [b3da866] Request failed: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies. ()
```
I've checked if node.js is installed in the docker and seems that it's not the case.
